import { borderWidth, radius, size, sizeH, sizeW } from '../tokens/border';
import { palette } from '../tokens/colors';
import { gap, spacingX, spacingY } from '../tokens/spacing';
import { fontFamily, fontSize, fontWeight } from '../tokens/typography';

export const darkTheme = {
  colors: {
    ...palette,
    background: palette.darkBackground,
    card: palette.neutral900,
    border: palette.neutral700,
    bodyText: palette.white,
    labelText: palette.charcoal100,
    mutedText: palette.neutral400,
    subtitleText: palette.neutral400,
    taglineText: palette.neutral400,
    linkText: palette.blue500,
    buttonDefaultBg: palette.white,
    buttonDefaultText: palette.black,
    buttonOutlineText: palette.neutral100,
    buttonRipple: 'rgba(255, 255, 255, 0.1)',
    inputBg: palette.neutral800,
    inputBorder: palette.neutral700,
    inputFocusBorder: palette.neutral300,
    inputText: palette.white,
    selectOptionBg: palette.neutral800,
    settingsContainerBg: palette.neutral800 as unknown as 'transparent',
    settingsBorder: palette.neutral700,
    settingsValueText: palette.white,
    modalHandle: palette.modalHandleDark,
    modalTitleText: palette.white,
    closeIconFill: palette.white,
    progressFill: palette.white,
    progressTrack: palette.neutral700,
    checkboxMuted: palette.checkboxMuted,
    iconMuted: palette.neutral500,
    modalBackdrop: palette.modalBackdrop,
    isDark: true,
  },
  paddingX: spacingX,
  paddingY: spacingY,
  marginX: spacingX,
  marginY: spacingY,
  gap,
  borderWidth,
  radius,
  size,
  sizeW,
  sizeH,
  fontFamily,
  fontSize,
  fontWeight,
};
