import { borderWidth, radius, size, sizeH, sizeW } from '../tokens/border';
import { palette } from '../tokens/colors';
import { gap, spacingX, spacingY } from '../tokens/spacing';
import { fontFamily, fontSize, fontWeight } from '../tokens/typography';

export const lightTheme = {
  colors: {
    ...palette,
    background: palette.white,
    card: palette.white,
    border: palette.charcoal100,
    bodyText: palette.black,
    labelText: palette.label,
    mutedText: palette.neutral500,
    subtitleText: palette.gray500,
    taglineText: palette.gray600,
    linkText: palette.blue500,
    buttonDefaultBg: palette.black,
    buttonDefaultText: palette.white,
    buttonOutlineText: palette.black,
    inputBg: palette.neutral100,
    inputBorder: palette.neutral300,
    inputFocusBorder: palette.neutral400,
    inputText: palette.black,
    selectOptionBg: palette.white,
    settingsContainerBg: 'transparent',
    settingsBorder: palette.charcoal100,
    settingsValueText: palette.neutral600,
    modalHandle: palette.modalHandleLight,
    modalTitleText: palette.modalTitleLight,
    closeIconFill: palette.neutral300,
    progressFill: palette.black,
    progressTrack: palette.progressTrack,
    checkboxMuted: palette.checkboxMuted,
    iconMuted: palette.iconMuted,
    modalBackdrop: palette.modalBackdrop,
    isDark: false,
  },
  paddingX: spacingX,
  paddingY: spacingY,
  marginX: spacingX,
  marginY: spacingY,
  gap,
  borderWidth,
  radius,
  size,
  sizeW,
  sizeH,
  fontFamily,
  fontSize,
  fontWeight,
};
